import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Breadcrumbs, Button, Container } from '@components/ui';
import { withPageLayoutData } from '@utils/index';
import { useTranslation } from 'next-i18next';

const Home: NextPage = () => {
  const { t } = useTranslation('common');
  return (
    <div>
      <Head>
        <title>{t('example.page_title')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div className="text-center my-4">
          <h1 className="font-bold text-3xl">{t('example.header')}</h1>
          <p className="font-medium text-lg">{t('example.text')}</p>
        </div>
        <div className="mx-auto w-fit">
          <Image width={647} height={647} src="https://c.tenor.com/2w1XsfvQD5kAAAAC/hhgf.gif" alt="excited" />
          <Button className="mt-1" ctaLink="/" type="secondary">
            Testlinkje
          </Button>
          <Breadcrumbs
            items={[
              { id: '', link: 'asafsfs', name: 'asfasfa' },
              { id: 'asfsaf', link: 'asaasdfsfs', name: 'asfasfa' }
            ]}
          />
        </div>
      </Container>
    </div>
  );
};

export const getServerSideProps = withPageLayoutData(async (_, locale: string) => {
  // Collect specific page data here
  const examplePageData = { locale };

  return {
    props: { examplePageData },
    notFound: !examplePageData
  };
});

export default Home;
