import Container from '@components/ui/container/container.component';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Container>
      <div className="text-center my-4">
        <h1 className="font-bold text-3xl">LiveWall NextJS Boilerplate</h1>
        <p className="font-medium text-lg">Succesvol geinstalleerd, je kan beginnen!</p>
      </div>
      <div className="mx-auto w-fit">
        <Image width={647} height={647} src="https://c.tenor.com/2w1XsfvQD5kAAAAC/hhgf.gif" alt="excited" />
      </div>
    </Container>
  </div>
);

export default Home;
